Product/urls.py
from django.conf.urls import url
from . import views

app_name = 'product'


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url (r'^(?P<category_slug>[-\w]+)/$', views.index, name='product_list_by_category'),
    url (r'^Drug/(?P<drug_slug>[-\w]+)/$', views.details, name='detail'),

    # comment url
    url(r'^comment/create-comment/', views.Add_comment, name='add-comment'),
]

cart/urls.py
from django.conf.urls import url
from . import views



app_name='cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name = 'cart_detail'),
    url(r'^add/(?P<drug_id>\d+)/$', views.cart_add, name= 'cart_add'),
    url(r'^remove/(?P<drug_id>\d+)/$', views.cart_remove, name= 'cart_remove')

]

orders/urls.py
from django.conf.urls import url
from . import views

app_name='order'
urlpatterns= [
    #url(r'^create/$', views.order_create, name='order_create'),
    url(r'^order-info/$', views.order_info, name='order_info'),
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    #url(r'^checkout/(?P<pk>[0-9]+)$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^checkout-successful/$', views.Checkout_Successfull , name='checkout-successful'),

]

pharmacy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from .views import Home, Privacy, Terms,test,contact_us
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home,name='home'),
    url(r'^privacy-and-policy$',Privacy , name='privacy'),
    url(r'^Terms-and-conditions$', Terms, name='terms'),
    url(r'^compound-info/', include('medicalspa.urls', namespace='compound-info')),
    url(r'^emergency/', include('emergency.urls', namespace='emergency')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^product/', include('Product.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^refill/', include('refill.urls', namespace='refill')),
    url(r'^user/', include('user_profile.urls')),

    # password
    url(r'password/$', password_reset,{'template_name': 'password_reset/password_reset.html'}, name='reset_password'),
    url(r'password/done/$', password_reset_done,{'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,{'template_name': 'password_reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'password/complete/$', password_reset_complete,{'template_name': 'password_reset/password_reset_complete.html'},  name='password_reset_complete'),

    # test
    url(r'^test/',test ),

    # other
    url(r'^contact-us$', contact_us,name='contact-us'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/forms.py
from django import forms

drug_quantity_choices = [(i, str(i)) for i in range(1, 21)]

class CartADDDrugForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=drug_quantity_choices, coerce=int)
    update= forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

cart/views.py
from django.shortcuts import render , redirect, get_object_or_404
from django.views.decorators.http import require_POST
from Product.models import Drug
from .cart import Cart
from .forms import CartADDDrugForm
from django.http import HttpResponse, JsonResponse


def cart_add(request, drug_id):
    cart =Cart(request)
    drug = get_object_or_404(Drug, id = drug_id)
    if request.method=='POST':
        form = CartADDDrugForm(request.POST)
        if form.is_valid():
            cart.add(drug=drug, quantity=request.POST['quantity'], update_quantity=True)
        return redirect('cart:cart_detail')
    else:
        cart.add(drug = drug, quantity= 1, update_quantity= False)
    status={
        'len':cart.len(),
        'status':cart.status
    }
    return JsonResponse(status)

def cart_remove(request, drug_id):
    cart = Cart(request)
    drug = get_object_or_404(Drug, id= drug_id)
    cart.remove(drug)
    return redirect('cart:cart_detail')

def cart_detail(request):
    cart = Cart(request)
    drug=Drug.objects.all()
    # return HttpResponse(cart)
    return render(request, 'cart/detail.html', {'cart': cart})

cart/templates/cart/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    your order cart
{% endblock %}
{% block style %}
    <style>
    .table>tbody>tr>td, .table>tbody>tr>th, .table>tfoot>tr>td, .table>tfoot>tr>th, .table>thead>tr>td, .table>thead>tr>th{
        vertical-align: middle;
    }
    </style>
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="container-fluid">

    <h1 class="text-center">your order cart</h1>
    <p class="text-center" style="height: 5px;width: 120px;border-radius: 5px;background-color: #1e7e34;margin: auto"></p>
        <br>
<div class="" style="width: 80%;margin: auto">
{% if cart.len > 0 %}
    <table class="table table-striped">

        <thead class="thead-dark">
            <tr>
                <th>#</th>
                <th>Medicine</th>
                <th>price</th>
                <th>quantity</th>
                <th>Remove</th>
            </tr>
        </thead>
        <tbody>

        {% for item in cart %}
            {% with drug=item.drug %}
            <tr>
                <td>
                    {% if drug.drug_pic %}
                    <a href="{{ drug.get.absolute_url }}">
                        <img src="{{ drug.drug_pic.url }}" width="100px" height="100px">
                    </a>
                    {% else %}
                        <img src="{% static 'icons/drugs.png' %}" alt="" width="100px" height="100px">
                    {% endif %}
                    
                </td>
                <td>{{ drug.drug_name }}</td>
                <td>{{ drug.price }}</td>
                <td>

                    <form action="{% url 'cart:cart_add' drug.id %}" method="post">
                        <input type="number" name="quantity" value="{{ item.quantity }}" min="1">
                        <input type="hidden" name="update" value="True" >
                        <button class="btn btn-success" type="submit" style="padding: 5px"><i class="fa fa-check-circle-o" aria-hidden="true"></i> update</button>
                        {% csrf_token %}
                    </form>
                </td>
                <td><a class="btn btn-danger" href="{% url 'cart:cart_remove' drug.id %}"><i class="fa fa-trash" aria-hidden="true"></i></a></td>
            </tr>
            {% endwith %}
        {% endfor %}
        <tr class="total">
            <td>Total</td>
            <td colspan="4" id="sum"></td>
        </tr>
        </tbody>
    </table>
    <p class="">
        <a class="btn btn-warning" href="{% url 'product:index' %}" ><i class="fa fa-chevron-left" aria-hidden="true"></i> countinue shopping</a>
         {% if request.user.is_authenticated %}
        <a class="btn btn-success" style="float: right" href="{% url 'orders:order_info' %}" >checkout <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
             {% else %}
                 <a class="btn btn-success" style="float: right" data-toggle="modal" data-target="#login">checkout <i class="fa fa-chevron-right" aria-hidden="true"></i></a>
            {% endif %}
    </p>
    {% else %}
        <div class="well text-center" style="width: 60%;margin: 50px auto">
            <h3 class="">you didn't chose anything</h3>
            <a class="btn btn-success " href="{% url 'product:index' %}"><i class="fa fa-shopping-basket" aria-hidden="true"></i> keep looking</a>
        </div>

    {% endif %}
    </div>
    </div>

    <script>

        $(document).ready(function () {
            var sum=0
             {% for item in cart %}
                  {% with drug=item.drug %}
                    sum=sum+({{ drug.price}}*{{item.quantity }})
                  {% endwith %}
             {% endfor %}
            $('#sum').html(sum)
        })
    </script>
{% endblock %}