Product/urls.py
from django.conf.urls import url
from . import views

app_name = 'product'


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url (r'^(?P<category_slug>[-\w]+)/$', views.index, name='product_list_by_category'),
    url (r'^Drug/(?P<drug_slug>[-\w]+)/$', views.details, name='detail'),

    # comment url
    url(r'^comment/create-comment/', views.Add_comment, name='add-comment'),
]

cart/urls.py
from django.conf.urls import url
from . import views



app_name='cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name = 'cart_detail'),
    url(r'^add/(?P<drug_id>\d+)/$', views.cart_add, name= 'cart_add'),
    url(r'^remove/(?P<drug_id>\d+)/$', views.cart_remove, name= 'cart_remove')

]

emergency/urls.py
from django.conf.urls import url
from . import views

app_name= 'emergency'
urlpatterns= [
    url(r'^emergency-info/$', views.Emergency_info, name='emergency-info'),
    url(r'^emergency-as-guest/$', views.Emergency_as_qeust_view, name='emergency-as-guest'),
    url(r'^report/emergency-as-guest/$', views.report_emergency_asguest, name='emergency-report'),

]

orders/urls.py
from django.conf.urls import url
from . import views

app_name='order'
urlpatterns= [
    #url(r'^create/$', views.order_create, name='order_create'),
    url(r'^order-info/$', views.order_info, name='order_info'),
    url(r'^checkout/$', views.CheckoutView.as_view(), name='checkout'),
    #url(r'^checkout/(?P<pk>[0-9]+)$', views.CheckoutView.as_view(), name='checkout'),
    url(r'^checkout-successful/$', views.Checkout_Successfull , name='checkout-successful'),

]

pharmacy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from .views import Home, Privacy, Terms,test,contact_us
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home,name='home'),
    url(r'^privacy-and-policy$',Privacy , name='privacy'),
    url(r'^Terms-and-conditions$', Terms, name='terms'),
    url(r'^compound-info/', include('medicalspa.urls', namespace='compound-info')),
    url(r'^emergency/', include('emergency.urls', namespace='emergency')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^product/', include('Product.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^refill/', include('refill.urls', namespace='refill')),
    url(r'^user/', include('user_profile.urls')),

    # password
    url(r'password/$', password_reset,{'template_name': 'password_reset/password_reset.html'}, name='reset_password'),
    url(r'password/done/$', password_reset_done,{'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,{'template_name': 'password_reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'password/complete/$', password_reset_complete,{'template_name': 'password_reset/password_reset_complete.html'},  name='password_reset_complete'),

    # test
    url(r'^test/',test ),

    # other
    url(r'^contact-us$', contact_us,name='contact-us'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

refill/urls.py
from django.conf.urls import url
from . import views

app_name= 'refill'
urlpatterns= [
    url(r'^new-rx/$', views.new_rx, name='new-rx'),
    url(r'^new-rx/checkout/(?P<pk>[0-9]+)/$', views.NewRx_checkout, name='new-rx-checkout'),
    url(r'^new-rx/checkout-payment/$', views.NewRx_CheckoutView.as_view(), name='newrx-checkoutview'),
    url(r'^new-rx/checkout-successful/$', views.Checkout_Successfull, name='new-rx-checkout-successful'),
    # report html
    url(r'^report/NewRx/$', views.report_newRx, name='report'),
    url(r'^report/NewRx-as-guest/$', views.report_newRx_asguest, name='report-newrx'),
    url(r'^report/refill-as-guest/$', views.report_refill_asguest, name='report-refill'),
    # ajax
    url(r'^ajax/$', views.ajax, name='ajax'),

    # qeust
    url(r'^refill_as_qeust/$', views.refill_as_qeust, name='refill-as-qeust'),
    url(r'^newrx_as_qeust/$', views.newrx_as_qeust, name='newrx-as-qeust'),


    # one click refill
    url(r'^$', views.refill_objects_list, name='refill'),
    url(r'^easy-refill/(?P<pk>[0-9]+)/$', views.refill_submit, name='refill-submit'),


]

user_profile/urls.py
from django.conf.urls import url
from . import views
from refill.views import refill_objects_list,refill_submit
app_name = 'user_profile'

urlpatterns = [
    url(r'^register', views.UserFormView.as_view(), name = 'register'),
    url(r'^login', views.LoginView.as_view(), name = 'login'),
    url(r'^logout', views.Logout, name = 'logout'),

    # userinfo
    url(r'^create-info', views.user_info, name='create-userinfo'),
    #consulting
    url(r'^consulting/ask', views.consulting_ask, name='consulting_ask'),
    url(r'^consulting/show/(?P<pk>[0-9]+)/$', views.consulting_show, name='consulting-show'),
    url(r'^consulting/$', views.consulting, name='consulting'),
    url(r'^consulting-as-guest/$', views.consultiong_as_qeust_view, name='consulting-as-guest'),
    url(r'^report/consulting-as-guest/$', views.report_consulting_asguest, name='report-consulting-as-guest'),
    #profile
    url(r'^$', views.profile, name='profile'),
    url(r'^update', views.EditView.as_view(), name='update'),
    url(r'^changepassword', views.ChangePassword, name='password'),

    url(r'^orders', views.order, name='orders'),
    url(r'^orders', views.order, name='orders'),


    # add phone
    url(r'^add-phone', views.add_phone, name='add-phone'),

]

orders/models.py
from django.db import models
from Product.models import Drug
from user_profile.models import UserInfo

class Order(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    paid = models.BooleanField(default=False)
    verified = models.BooleanField(default=False)
    sent=models.BooleanField(default=False)
    shiping_method_choices =(
        ( '7.5', 'express one day shiping $7.5'),
        ( '0', 'regular three day shiping'  ),
    )
    shiping_method=models.CharField(choices=shiping_method_choices,default='0', max_length=50)
    info = models.ForeignKey(UserInfo,null=True,related_name='info')
    class Meta:
        ordering= ('-created',)

    def __str__(self):
        return 'Order{}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items')
    drug = models.ForeignKey(Drug, related_name='order_items')
    price = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity

orders/forms.py
from django import forms
from .models import Order
from cart.cart import Cart
from django.utils.translation import ugettext_lazy as _
from decimal import Decimal

class CheckoutForm(forms.Form):
    payment_method_nonce = forms.CharField(
        max_length=1000,
        widget=forms.widgets.HiddenInput,
        required=False,  # In the end it's a required field, but I wanted to provide a custom exception message
    )
    #amount= forms.DecimalField(max_digits=10, decimal_places=2,)



    def clean(self):
        self.cleaned_data = super(CheckoutForm, self).clean()
        # Braintree nonce is missing
        if not self.cleaned_data.get('payment_method_nonce'):
            raise forms.ValidationError(_(
                'We couldn\'t verify your payment. Please try again.'))
        return self.cleaned_data


    #def amount_to_pay(self, request):
     #   order_id = request.session.get['order.id']
      #  order = Order.objects.get(pk= order.id)
       # self.initial['amount']= order.get_total_cost()

orders/views.py
from django.shortcuts import render, redirect
from user_profile.models import UserInfo
from .models import OrderItem,Order
from cart.cart import Cart
from pharmacy.report import render_to_pdf
import braintree
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse,reverse_lazy
from django.utils.decorators import method_decorator
from django.views import generic
from . import forms
from pharmacy import settings
from django.utils.translation import ugettext_lazy as _
from .forms import    CheckoutForm
from django.http import HttpResponse
from django.conf import settings
from decimal import Decimal
from django.core.mail import send_mail
from django.template.loader import render_to_string

def order_info(request):
    user=request.user
    info=UserInfo.objects.filter(user=request.user)
    cart = Cart(request)
    total = 0
    for item in cart:
        total+=(item['price']* int(item['quantity']))
    total= str(total)
    if request.method=='POST':
        info = UserInfo.objects.get(pk=request.POST['info'])
        order = Order.objects.create(info=info)
        order.shiping_method=request.POST['shiping_method']
        order.save()
        request.session['order.id'] = order.id
        for item in cart:
            OrderItem.objects.create(order=order,
                                     drug=item['drug'],
                                      price=item['price'],
                                     quantity=item['quantity'])

            cart.clear()
        return redirect(reverse('order:checkout'))
        #return reverse_lazy('orders:checkout',kwargs={'pk':pk})
        #return render(request, 'orders/checkout.html', {'order': order})
    else:

        return render(request,'orders/info-chek.html',{'info':info,'cart':cart,'user':user, 'total':total})


"""
Adds simple form view, which communicates with Braintree.

There are four steps to finally process a transaction:

1. Create a client token (views.py)
2. Send it to Braintree (js)
3. Receive a payment nonce from Braintree (js)
4. Send transaction details and payment nonce to Braintree (views.py)

"""

class CheckoutView(generic.FormView):
    """This view lets the user initiate a payment."""
    form_class = forms.CheckoutForm
    template_name = 'orders/checkout.html'
    success_url = 'order:checkout-successful'

    #def total_amount(self):
     #   request=self.request
      #  order_id = request.session['order.id']
        #order= Order.objects.get(pk = order_id)
        #amount = order.get_total_cost()
        #shipment = Decimal(order.shiping_method)
        #total_amount = amount + shipment
        #return render(request, {'total_amount':total_amount})


    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        # We need the user to assign the transaction
        self.user = request.user
        # Ha! There it is. This allows you to switch the
        # Braintree environments by changing one setting
        if settings.BRAINTREE_PRODUCTION:
            braintree_env = braintree.Environment.Production
        else:
            braintree_env = braintree.Environment.Sandbox

        # Configure Braintree
        braintree.Configuration.configure(
            braintree_env,
            merchant_id=settings.BRAINTREE_MERCHANT_ID,
            public_key=settings.BRAINTREE_PUBLIC_KEY,
            private_key=settings.BRAINTREE_PRIVATE_KEY,
        )

        # Generate a client token. We'll send this to the form to
        # finally generate the payment nonce
        # You're able to add something like ``{"customer_id": 'foo'}``,
        # if you've already saved the ID
        self.braintree_client_token = braintree.ClientToken.generate({})
        return super(CheckoutView, self).dispatch(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        request = self.request
        order_id = request.session['order.id']
        order = Order.objects.get(pk=order_id)
        amount = order.get_total_cost()
        shipment = Decimal(order.shiping_method)
        total_amount = (amount + shipment)
        ctx = super(CheckoutView, self).get_context_data(**kwargs)
        ctx.update({
            'braintree_client_token': self.braintree_client_token,
            'total_amount':total_amount,
            'order':order,
            'amount':amount,
        })
        return ctx

    def form_valid(self, form):
        # Braintree customer info
        # You can, for sure, use several approaches to gather customer infos
        # For now, we'll simply use the given data of the user instance
        customer_kwargs = {
            "first_name": self.user.first_name,
            "last_name": self.user.last_name,
            "email": self.user.email,

        }

        # Create a new Braintree customer
        # In this example we always create new Braintree users
        # You can store and re-use Braintree's customer IDs, if you want to
        result = braintree.Customer.create(customer_kwargs)
        if not result.is_success:
            # Ouch, something went wrong here
            # I recommend to send an error report to all admins
            # , including ``result.message`` and ``self.user.email``

            context = self.get_context_data()
            # We re-generate the form and display the relevant braintree error
            context.update({
                'form': self.get_form(self.get_form_class()),
                'braintree_error': u'{} {}'.format(
                    result.message, _('Please get in contact.'))
            })
            return self.render_to_response(context)
        # If the customer creation was successful you might want to also
        # add the customer id to your user profile
        customer_id = result.customer.id
        """
        Create a new transaction and submit it.
        I don't gather the whole address in this example, but I can
        highly recommend to do that. It will help you to avoid any
        fraud issues, since some providers require matching addresses

        """
        address_dict = {
            "first_name": self.user.first_name,
            "last_name": self.user.last_name,
            "street_address":"300 E longleaf dr",
            "extended_address": 'auburn',
            "locality": 'auburn',
            #"region": 'state_or_region',
            "postal_code": '36832',
            #"country_code_alpha2": 'alpha2_country_code',
            #"country_code_alpha3": 'alpha3_country_code',
            #"country_name": 'country',
            #"country_code_numeric": 'numeric_country_code',
        }
        # You can use the form to calculate a total or add a static total amount
        # I'll use a static amount in this example
        request = self.request
        order_id = request.session['order.id']
        order = Order.objects.get(pk=order_id)
        amount = order.get_total_cost()
        shipment = Decimal(order.shiping_method)
        total_amount = amount + shipment
        result = braintree.Transaction.sale({
            "customer_id": customer_id,
            "amount": total_amount,
            "payment_method_nonce": form.cleaned_data['payment_method_nonce'],
            "descriptor": {
                #Definitely check out https://developers.braintreepayments.com/reference/general/validation-errors/all/python#descriptor
                "name": "COMPANY*test",

           },
            "billing": address_dict,
            "shipping": address_dict,
            "options": {
                # Use this option to store the customer data, if successful
                'store_in_vault_on_success': True,
                # Use this option to directly settle the transaction
                # If you want to settle the transaction later, use ``False`` and later on
                # ``braintree.Transaction.submit_for_settlement("the_transaction_id")``
                'submit_for_settlement': True,
            },
        })
        if not result.is_success:
            # Card could've been declined or whatever
            # I recommend to send an error report to all admins
            # , including ``result.message`` and ``self.user.email``

            context = self.get_context_data()
            context.update({
                'form': self.get_form(self.get_form_class()),
                'braintree_error': _(
                   'Your payment could not be processed. Please check your'
                    ' input or use another payment method and try again.')
            })
            return self.render_to_response(context)

        # Finally there's the transaction ID
        # You definitely want to send it to your database
        transaction_id = result.transaction.id
        # Now you can send out confirmation emails or update your metrics
        # or do whatever makes you and your customers happy :)
        order.paid = True
        order.save()
        # report
        pdf = render_to_pdf('report/shop-report.html', {'order':order,'total':total_amount})  # todo send fax and sms and email
        # email
        msg = render_to_string('email/shop-factor.html',
                               {'order': order,
                                'total':total_amount})
        send_mail('Thank you', 'your order is successfuly submited',
                  settings.DEFAULT_FROM_EMAIL, [self.request.user.email], fail_silently=False,html_message=msg),
        return super(CheckoutView, self).form_valid(form)

    def get_success_url(self):
        return reverse(self.success_url)


def Checkout_Successfull(request):
    return render(request, 'orders/created.html')

user_profile/templates/user_profile/change_password.html
{% extends 'base/profile-base.html' %}
{% block content %}
 <div class="container-fluid">
    <div class="row">
        <br>
        <br>
    <div class="col-md-8 col-md-offset-2 col-xs-12 " >
    <h3 style="color: #848484;">update Your Password</h3>
    <div style="padding: 10px;background-color: white;border-radius: 10px">
    <form method="post" action="" class="form-horizontal">
 {% csrf_token %}
    {% for field in form %}
              <div class="form-group" style="margin: 0">

                <span>{{ field.errors }}</span>
                <label>{{ field.label_tag }}</label>

              <input class="form-control" type="password" name="{{ field.name }}">
              </div>
        {% endfor %}

        <br>
        <button class="btn btn-success" type="submit" >Submit</button>

</form>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

user_profile/templates/user_profile/dashboard.html
{% extends "base/profile-base.html" %}
{% load static %}
{% block title %} {{ user.username }}{% endblock %}
{% block activeClass %}dashboard{% endblock %}
{% block style %}
    <style>
    p{
        font-size: 20px;
    }
    .title{
        color: #939393;
    }
    .tile{
            background-color: #fefefe;
            -webkit-box-shadow: 0 1px 2.5px 0 rgba(0,0,0,.15);
            box-shadow: 0 1px 2.5px 0 rgba(0,0,0,.15);
            transition: .4s;
            padding: 10px;
            position: relative;

        }

        .tile:hover{
            box-shadow: 0 6px 15px rgba(0,0,0,.15);
            -webkit-box-shadow: 0 6px 15px rgba(0,0,0,.15)
        }
    .data{
        color: #007bff;
    }
    .table>tbody>tr>td{
        vertical-align: middle;
    }
    </style>
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="container-fluid">
    <div class="row">
        <div class="col-xs-12">
            <h2 class='title'>Information</h2>
            <div class="tile">
                <table class="table table-bordered">
                    <tr>
                        <td>Name: <span class="data">{{ user.get_full_name }}</span></td>
                        <td>Email: <span class="data">{{ user.email }}</span></td>
                        <td>Phone number: {% if user.phone_number %}<span class="data">{{ user.phone_number }}</span>{% else %}<a href="{% url 'user_profile:add-phone' %}">add phone number</a>{% endif %}</td>
                    </tr>
                </table>
                <a href="{% url 'user_profile:update' %}" class="btn btn-primary">Edit your Information</a>
                <a href="{% url 'user_profile:password' %}" class="btn btn-default">Chaneg password</a>
            </div>
        </div>
    </div>
        <br>
        <br>
    <div class="row">
        <div class="col-xs-12">
            <h2 class="title">Performance Report</h2>
            <div class="tile">
                <table class="table table-bordered">
                    <tr>
                        <td>Total NewRx and Refill Order: <span class="data">{{ refill_all.count }}</span> </td>
                        <td>Verifyed NewRx and Refill Orders: <span class="data">{{ refill_verfied.count }} </span></td>
                        <td>waiting to pay orders: <span class="data">{{ refill_pay.count }} </span> <a href="{% url 'user_profile:orders' %}#newrx" style="float: right">Payment</a></td>
                    </tr>
                    <tr>
                        <td>Total Orders from Shop (product orders): <span class="data">{{ free_all.count }}</span></td>
                        <td></td>
                        <td></td>
                    </tr>
                </table>
                <a href="{% url 'user_profile:orders' %}" class="btn btn-primary">Mange All Orders</a>
            </div>
        </div>
    </div>
        <br>
        <br>
    <div class="row">
        <div class="col-xs-12">
            <h2 class="title">Consulting Summery</h2>
            <div class="tile">
                <table class="table table-bordered">
                    <tr>
                        <td>Total Questions: <span class="data">{{ questions.count }}</span></td>
                        <td>Total Answer: <span class="data">{{ answer.count}}</span></td>
                        <td>Last Question: <span class="data">{{ questions.last.date}}</span></td>
                    </tr>
                </table>
                <a href="{% url 'user_profile:consulting_ask' %}" class="btn btn-primary">Ask New Question</a>
                <a href="{% url 'user_profile:consulting' %}" class="btn btn-default">Manage Your Question</a>
            </div>
        </div>
    </div>
        <br>
        <br>
    <div class="row">
        <div class="col-xs-12">
            <h2 class="title">Delivery Addresses</h2>
            <div class="tile">
                <div class="row">
                {% if info %}
                <div class="col-sm-11 col-xs-11" style="height: 330px;overflow-x: scroll;">
                    <div style="width: {% widthratio info.count 1 600 %}px;height: 301px;margin-bottom:0;display: flex">
                        {% for i in info %}
                            <div class="panel panel-default" style="height: 300px;width:300px;background-color: #f8f8f8;border-radius: 4px;border: 2px darkgrey solid;flex: 1;margin-right: 10px">
                                <div class="panel-heading">address</div>
                                <div class="panel-body">
                                    <p style="height: 50px">address : {{ i.address }}</p>
                                    <hr>
                                    <p>City : {{ i.city }}</p>
                                    <p>State : {{ i.city }}</p>
                                    <p>Zip : {{ i.zip }}</p>
                                </div>
                                <div class="panel-footer text-center">
                                    <input type="radio" name="info" id="info{{ forloop.counter }}" value="{{ i.pk }}"> chose this address
                                </div>
                            </div>
                        {% endfor %}
                        <div class="panel panel-default hover-cours" data-toggle="modal" data-target="#add-address" style="height: 300px;width:300px;background-color: #f8f8f8;border-radius: 4px;border: 2px darkgrey solid;flex: 1">
                            <img src="{% static 'orders/add.png' %}" alt="" width="100%" height="100%">
                        </div>
                    </div>
                </div>
                <div class="col-sm-1 col-xs-1 text-center" style="background-color: #f7f7f7;height: 301px;padding: 0;border-radius: 10px">
                    <p class=""style="position: absolute;right: 10%;top:40%;font-size: 50px"><i class="fa fa-chevron-right" aria-hidden="true"></i></p>
                </div>
                 {% else %}
                    <div class="col-xs-12 text-center">
                        <h4>For submit any orders we need you delivery address</h4>
                        <a href="{% url 'user_profile:create-userinfo' %}" class="btn btn-primary">Add it now</a>

                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
        <br>
        <br>
    </div>
{% endblock %}

user_profile/templates/user_profile/form.html
{% extends 'base/profile-base.html' %}
{% block content %}
 <div class="container-fluid">
    <div class="row">
        <br>
        <br>
    <div class="col-md-8 col-md-offset-2 col-xs-12 " >
    <h3 style="color: #848484;">update yout informations</h3>
    <div style="padding: 10px;background-color: white;border-radius: 10px">
    <form method="post" action="" class="form-horizontal">
 {% csrf_token %}
    {% for field in form %}
              <div class="form-group" style="margin: 0">

                <span>{{ field.errors }}</span>
                <label>{{ field.label_tag }}</label>
{#                <div class="">{{ field }}</div>#}
              <input class="form-control" type="text" name="{{ field.name }}" value="{{ field.initial }}">
              </div>
        {% endfor %}

        <br>
        <button class="btn btn-success" type="submit" >Submit</button>

</form>
    </div>
    </div>
    </div>
    </div>
{% endblock %}

user_profile/templates/user_profile/profile.html
{% extends "base/profile-base.html" %}

{% block title %} {{ user.username }}{% endblock %}
{% block style %}
    <style>
    p{
        font-size: 20px;
    }
    </style>
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="container-fluid">
    <div class="row">
        <div class="col-md-4 col-xs-12">
            <div class="text-center" style="border-radius: 5px;background-color: #fff;height: 250px;padding: 5px;margin-bottom: 10px;box-shadow:10px 10px 10px #c6c6c6;">
                <h3>Emergency orders</h3><br>
                {% if not eme_all %}
                    <p class="text-center">you didn't order any emergency medicine</p>
                    <a class=" btn btn-success" style="margin: auto" href="{% url 'emergency:emergency-info' %}">order now</a>
                {% else %}
                    <p>all orders: {{ eme_all.count }}</p>
                    <p>verified orders: {{ eme_verified.count }}</p>
                    <a class=" btn btn-success" style="margin: auto" href="{% url 'user_profile:emergency-order' %}">more details</a>

                {% endif %}
            </div>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="text-center" style="border-radius: 5px;background-color: #fff;height: 250px;padding: 5px;margin-bottom: 10px;box-shadow:10px 10px 10px #c6c6c6;">
                <h3>Refill orders</h3><br>
                {% if not refill_all %}
                    <p class="text-center">you didn't order any refill medicine</p>
                    <a class=" btn btn-success" style="margin: auto" href="{% url 'refill:new-rx' %}">order now</a>
                {% else %}
                    <p>all orders: {{ refill_all.count }}</p>
                    <p>verified orders: {{ refill_verfied.count }}</p>
                    <a class=" btn btn-success" style="margin: auto" href="{% url 'user_profile:refill-order' %}">more details</a>

                {% endif %}
            </div>
        </div>
        <div class="col-md-4 col-xs-12">
            <div class="text-center" style="border-radius: 5px;background-color: #fff;height: 250px;padding: 5px;margin-bottom: 10px;box-shadow:10px 10px 10px #c6c6c6;">
                <h3>free product orders</h3><br>
                {% if not free_all %}
                    <p class="text-center">you didn't order any free product medicine</p>
                    <a class=" btn btn-success" style="margin: auto" href="{% url 'product:index' %}">order now</a>
                {% else %}
                    <p>all orders: {{ free_all.count }}</p>
                    <p>verified orders: {{ free_verified.count }}</p>
                    <a class=" btn btn-success" style="margin: auto" href="{% url 'user_profile:Free-Products-orders' %}">more details</a>

                {% endif %}
            </div>
        </div>
    </div>
        <br>
    <div class="row">
    <div class="col-xs-12" >
        <div class="text-center" style="border-radius: 5px;background-color: #fff;height: 250px;padding: 5px;margin-bottom: 10px;box-shadow:10px 10px 10px #c6c6c6;">
            <h1 >you can ask any quetion, we're here to answer</h1>
            <br>
            <a class=" btn btn-success" href="{% url 'user_profile:consulting' %}">ask you're question now!</a>
        </div>
    </div>
    </div>
    </div>
{% endblock %}

user_profile/templates/user_profile/profile_your_orders.html
{% extends "base/profile-base.html" %}

{% block title %} {{ user.username }} orders{% endblock %}
{% block style %}
    <style>
    p{
        font-size: 20px;
    }
    </style>
{% endblock %}
{% block content %}
    <div class="container-fluid">

    <h1 class="text-center">your orders</h1>
    <p class="text-center" style="height: 5px;width: 120px;border-radius: 5px;background-color: #1e7e34;margin: auto"></p>
        <br>
<div class="" style="width: 80%;margin: auto">
{% if refil_num > 0 %}
    <table class="table table-striped">

        <thead class="thead-dark">
            <tr>
                <th>order</th>
                <th>date</th>
                <th>verified</th>
                <th>payment status</th>
                <th>cancel</th>
            </tr>
        </thead>
        <tbody>

        {% for item in refilllist %}
            <tr>
                <td>{{ item}}</td>
                <td>{{ item.created }}</td>
                <td>{% if item.verified %}
                        verified
                    {% else %}
                        in process
                {% endif %}
                </td>
               <td>{% if item.paid %}
                        payment successful
                   {% else %}
                   proceed to payment gateway
               {% endif %}
               </td>


                <td>
                   {% now "Y-m-d" as todays_date %}
                    {% if todays_date == item.created|date:"Y-m-d" %}
                        {% if item.verified == False %}
                            {% if item.paid == False%}
                                 <a class="btn btn-danger" href=""><i class="fa fa-trash" aria-hidden="true"></i></a></td>
                            {% endif %}
                        {% endif %}
                    {% else%}
                    ......
            {% endif %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% else %}
    <h1>you have no orders submited by now</h1>
{% endif %}

{% endblock %}