Product/urls.py
from django.conf.urls import url
from . import views

app_name = 'product'


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url (r'^(?P<category_slug>[-\w]+)/$', views.index, name='product_list_by_category'),
    url (r'^Drug/(?P<drug_slug>[-\w]+)/$', views.details, name='detail'),

    # comment url
    url(r'^comment/create-comment/', views.Add_comment, name='add-comment'),
]

cart/urls.py
from django.conf.urls import url
from . import views



app_name='cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name = 'cart_detail'),
    url(r'^add/(?P<drug_id>\d+)/$', views.cart_add, name= 'cart_add'),
    url(r'^remove/(?P<drug_id>\d+)/$', views.cart_remove, name= 'cart_remove')

]

pharmacy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from .views import Home, Privacy, Terms,test,contact_us
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home,name='home'),
    url(r'^privacy-and-policy$',Privacy , name='privacy'),
    url(r'^Terms-and-conditions$', Terms, name='terms'),
    url(r'^compound-info/', include('medicalspa.urls', namespace='compound-info')),
    url(r'^emergency/', include('emergency.urls', namespace='emergency')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^product/', include('Product.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^refill/', include('refill.urls', namespace='refill')),
    url(r'^user/', include('user_profile.urls')),

    # password
    url(r'password/$', password_reset,{'template_name': 'password_reset/password_reset.html'}, name='reset_password'),
    url(r'password/done/$', password_reset_done,{'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,{'template_name': 'password_reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'password/complete/$', password_reset_complete,{'template_name': 'password_reset/password_reset_complete.html'},  name='password_reset_complete'),

    # test
    url(r'^test/',test ),

    # other
    url(r'^contact-us$', contact_us,name='contact-us'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.conf.urls import url
from . import views
from refill.views import refill_objects_list,refill_submit
app_name = 'user_profile'

urlpatterns = [
    url(r'^register', views.UserFormView.as_view(), name = 'register'),
    url(r'^login', views.LoginView.as_view(), name = 'login'),
    url(r'^logout', views.Logout, name = 'logout'),

    # userinfo
    url(r'^create-info', views.user_info, name='create-userinfo'),
    #consulting
    url(r'^consulting/ask', views.consulting_ask, name='consulting_ask'),
    url(r'^consulting/show/(?P<pk>[0-9]+)/$', views.consulting_show, name='consulting-show'),
    url(r'^consulting/$', views.consulting, name='consulting'),
    url(r'^consulting-as-guest/$', views.consultiong_as_qeust_view, name='consulting-as-guest'),
    url(r'^report/consulting-as-guest/$', views.report_consulting_asguest, name='report-consulting-as-guest'),
    #profile
    url(r'^$', views.profile, name='profile'),
    url(r'^update', views.EditView.as_view(), name='update'),
    url(r'^changepassword', views.ChangePassword, name='password'),

    url(r'^orders', views.order, name='orders'),
    url(r'^orders', views.order, name='orders'),


    # add phone
    url(r'^add-phone', views.add_phone, name='add-phone'),

]

Product/models.py
from django.db import models
from django.core.urlresolvers import reverse
from user_profile.models import User
from markdown_deux import markdown
from django.utils.safestring import mark_safe


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug =models.SlugField(max_length=100, db_index=True, unique=True)

    class Meta:
        ordering = ('name', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product:product_list_by_category', args=[self.slug])





class  Drug(models.Model):
    category= models.ForeignKey(Category,null=True , related_name='products')
    drug_name = models.CharField(max_length=100)
    dose = models.CharField(max_length=100)
    drug_company = models.CharField(max_length=100)
    drug_pic = models.ImageField(blank=True)
    description  = models.TextField(blank=True)
    drug_usage = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10,decimal_places=2)
    stock= models.PositiveIntegerField()
    available=models.BooleanField(default=True)
    slug = models.SlugField(unique=True, allow_unicode=True,null=True)
    drug_type=models.CharField(max_length=100, blank=True)
    over_the_counter = models.BooleanField(default=False)
    drug_ingredient = models.CharField(max_length=200, blank=True)
    created = models.DateTimeField(auto_now_add=True, null=True)

    class Meta :
        ordering = ('created', )


    def __str__(self):
        return self.drug_name+ ' , ' + self.dose

    def get_absolute_url(self):
        return reverse("product:detail",kwargs={"drug_slug": self.slug})

    def get_markdown(self):
        content = self.description
        markdown_text = markdown(content)
        return mark_safe(markdown_text)

class Comment(models.Model):
    user=models.ForeignKey(User,blank=True,null=True)
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    drug_slug=models.SlugField(allow_unicode=True)
    def __str__(self):
        return 'comment on '+ self.drug_slug

class ChildComment(models.Model):
    parrent=models.ForeignKey(Comment,related_name='child')
    user = models.ForeignKey(User, blank=True)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    drug_slug = models.SlugField(allow_unicode=True)

    def __str__(self):
        return 'reply on ' + self.drug_slug

Product/forms.py
from django import forms
from .models import Comment,ChildComment



class CommentForm(forms.ModelForm):
    class Meta:
        model=Comment
        fields = ['body','drug_slug']

class ChildCommentForm(forms.ModelForm):
    class Meta:
        model=ChildComment
        fields = ['body','drug_slug']

Product/views.py
from django.http import HttpResponse
from .models import Drug,Comment, Category
from django.shortcuts import render, get_object_or_404,redirect
from django.db.models import Q
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from cart.forms import CartADDDrugForm
from .forms import CommentForm,ChildCommentForm


def index(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    queryset_list = Drug.objects.all().order_by('-id')
    if category_slug:
        category= get_object_or_404(Category, slug=category_slug)
        queryset_list = queryset_list.filter(category=category)
    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(
            Q(drug_name__icontains=query) |
            Q(drug_company__icontains=query) |
            Q(drug_usage__icontains=query)

        ).distinct()
    paginator = Paginator(queryset_list, 12)
    page_request_var = "page"
    page = request.GET.get(page_request_var)
    try:
        queryset = paginator.page(page)
    except PageNotAnInteger:

        queryset = paginator.page(1)
    except EmptyPage:

        queryset = paginator.page(paginator.num_pages)

    context = {
        "drugs": queryset,
        "page_request_var": page_request_var,
        'categories': categories,
        'category': category,
    }
    return render(request, "product/index.html", context)



def details(request, drug_slug):
    drug = get_object_or_404(Drug, slug= drug_slug)
    cart_drug_form =CartADDDrugForm()
    comments=Comment.objects.filter(drug_slug=drug_slug)
    return render(request, 'product/detail.html', {'drug': drug,'cart_drug_form': cart_drug_form,'comment':comments})



def Add_comment(request):
    if request.method=="POST":
        # age comment parrent dashte bashe be onvane child comment save mishe
        if request.POST['parrent']:
            if request.user.is_authenticated:
                form=ChildCommentForm(request.POST)
                if form.is_valid():
                    post=form.save(commit=False)
                    parrent=Comment.objects.get(pk=request.POST['parrent'])
                    post.parrent=parrent
                    post.user=request.user
                    post.save()
                else:
                    return HttpResponse(form.errors)
        else:
            form=CommentForm(request.POST)
            if form.is_valid():
                post=form.save(commit=False)
                if request.user.is_authenticated:
                    post.user=request.user
                post.save()
            else:
                return HttpResponse(form.errors)
        return redirect(request.POST['redirect'])
    else:
        return HttpResponse('get')

Product/templates/product/detail.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}
    {{ drug_name }}
{% endblock %}
{% block style %}
    <style>
    .add-to-cart{

    }
{#    @media screen and (min-device-width: 768px){#}
{#        .add-to-cart{#}
{#            position: fixed;right: 20px;border-radius: 2px;box-shadow:5px 5px 20px #c7c7c7;height: 300px;z-index: 1000#}
{#        }#}
{##}
{#    }#}
    </style>
{% endblock %}
{% block content %}
    <br>
    <br>
    <br>
    <div class="container-fluid">
    <h1>{{drug.drug_name}}</h1>
    <h1>{{drug.drug_name}}</h1>
    <div class="col-sm-9 col-xs-12">
            {% if drug.drug_pic %}
                        <img id="zoom_01" src="{{ drug.drug_pic.url }}" width="80%" height="500px" >

                    {% else %}
                        <img src="{% static 'icons/drugs.png' %}" alt="" width="100px" height="100px">
            {% endif %}
        <br>
        <br>
        <br>
            <table class="table">

                <tr>
                    <th>name</th>
                    <th>{{drug.drug_name }}</th>
                </tr>
                <tr>
                    <th>dose</th>
                    <th>{{drug.dose }}</th>
                </tr>
                <tr>
                    <th>company</th>
                    <th>{{drug.drug_company }}</th>
                </tr>
                <tr>
                    <th>usage</th>
                    <th>{{drug.drug_usage }}</th>
                </tr>
            </table>
            <h2>moere detailes</h2>

            {{ drug.get_markdown }}
        <a class="btn btn-success" onclick="add_to_cart({{ drug.pk }})">add to cart for
        {% if drug.price == 0 %}
            <span class="disabled" style="font-size: 17px">Free!!</span>
            {% else %}
            <span class="disabled" style="font-size: 17px">{{ drug.price }}</span>
        {% endif %}
        </a>
    </div>
    <div class="col-sm-3 col-xs-12 add-to-cart" style="">
        <h3>get it now</h3>
        <h3>
        {% if drug.price == 0 %}
            <span class="disabled" style="font-size: 17px">Free!!</span>
            {% else %}
            <span class="disabled" style="font-size: 17px">{{ drug.price }}</span>
        {% endif %}
        </h3>
    <h4>you dont need to go to the store</h4>
        <a class="btn btn-success" style="width: 100%;background-color: #1e7e34" onclick="add_to_cart({{ drug.pk }})">
            add to cart for
            {% if drug.price == 0 %}
            <span class="disabled" style="font-size: 17px">Free!!</span>
            {% else %}
            <span class="disabled" style="font-size: 17px">{{ drug.price }}</span>
        {% endif %}
        </a>
    </div>
    </div>
    <br>
    <br>
    <br>
      {#  drug  comment section#}
    <div class="comment-tabs" style="width: 95%;margin: auto;margin-bottom: 10px;background-color: rgba(231, 231, 231,0.7);padding: 0 10px 0 10px; border-radius: 10px"  >
            <ul class="nav nav-tabs" role="tablist">
                <li class="active" style="float: right"><a href="#comments" role="tab" data-toggle="tab"><h4 class="reviews text-capitalize">Comments</h4></a></li>
                <li style="float: right"><a href="#add-comment" role="tab" data-toggle="tab"><h4 class="reviews text-capitalize">add Comment</h4></a></li>
           </ul>
        <div class="tab-content">
                <br>
                <div class="tab-pane active" id="comments">
                    {% for i in comment %}
                        <div class="panel panel-default">
                                <div class="panel-heading">
                                        <p class="panel-title">{{ i.user.username }}</p>

                                </div>
                            <div class="panel-body">{{ i.body }}
                            {% for y in i.child.all%}
                                <div class="panel panel-default" style="width: 90%;margin: auto">
                                    <div class="panel-heading">{{ y.user.username }}</div>
                                <div class="panel-body">{{ y.body }}</div>
                                </div>
                            {% endfor %}
                                <div class="row" style="width: 80%;margin: auto">
                                    <br>
                                    {% if request.user.is_authenticated  %}
                                    <form action="{% url 'product:add-comment'%}" method="post" class="form-horizontal" role="form">
                                        {% csrf_token %}
                                        <div class="col-lg-12">
                                            <div class="input-group">
                                                <input type="text" class="form-control" placeholder="type your answer" name="body">
                                                  <span class="input-group-btn">
                                                    <button class="btn btn-secondary" type="submit" style="background-color: #951768;color: white">submit</button>
                                                  </span>
                                            </div>
                                        </div>
                                        <input hidden name="redirect" value="{{ request.path }}">
                                        <input hidden name="drug_slug" value="{{ drug.slug }}">
                                        <input hidden name="parrent" value="{{ i.pk }}">
                                    </form>
                                    {% else %}
                                    <div class="text-center">
                                       <p> برای پاسخ نظر <a href="{% url 'user_profile:login' %}">وارد </a>یا <a href="{% url 'user_profile:register' %}">عضو</a> شوید</p>
                                    </div>
                                    {% endif %}
                            </div>


                            </div>
                        <hr>
                        </div>
                    {% endfor %}

                </div>

                <div class="tab-pane" id="add-comment">
                    {% if request.user.is_authenticated %}
                        <form action="{% url 'product:add-comment'%}" method="post" class="form-horizontal" role="form">
                            {% csrf_token %}
                            <p>{{ request.user.username }}</p>
                        <div class="form-group">
                            <div class="col-sm-10">
                                <textarea class="form-control" name="body" rows="5"></textarea>
                            </div>
                            <label for="email" class="col-sm-2 control-label">نظر</label>
                        </div>
                        <input hidden name="redirect" value="{{ request.path }}">
                        <input hidden name="drug_slug" value="{{ drug.slug }}">
                        <input hidden name="parrent" value="">

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button class="btn btn-success btn-circle text-uppercase" type="submit" id="submitComment"><span class="glyphicon glyphicon-send"></span>ثبت نظر</button>
                            </div>
                        </div>
                        </form>
                    {% else %}
                        <div class="text-center">
                           <p> برای ارسال نظر <a href="{% url 'user_profile:login' %}?next={{ request.path }}">وارد </a>یا <a href="{% url 'user_profile:register' %}?next={{ request.path }}">عضو</a> شوید</p>

                        </div>
                    {% endif %}

                </div>
            </div>
        </div>

    </div>
    <script type="text/javascript" src="{% static 'product/jquery.elevateZoom-3.0.8.min.js' %}"></script>
    <script>
        $("#zoom_01").elevateZoom({tint:true, tintColour:'#F90', tintOpacity:0.5,scrollZoom : true, zoomWindowWidth:500,
            zoomWindowHeight:400});
    </script>
{% endblock %}

Product/templates/product/index.html
{% extends 'base/base.html' %}
{% load static %}


{% block style %}
    <link rel="stylesheet" href="{% static 'product/product-list-style.css' %}">
{% endblock %}
{% block title %}
    {% if category %}{{ category.name }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}


<div class="container-fluid" style="background-color: #f1f1f1">
    <br>
    <br>



<div class="row">
<div class="col-sm-3  hidden-xs" style="padding: 10px;">
        <div class="affix" style="height: 200px;margin: auto;width: inherit;z-index: 1 ">
            <div style="background-color: #fff;margin-bottom: 10px;padding: 5px;">
                <h3>categouries</h3>
                <ul class="nav nav-pills nav-stacked">

        <li {% if not category %}class="active"{% endif %}>
            <a href="{% url 'product:index' %}">All</a>
        </li>
        {% for item in categories %}
            <li {% if category.slug == item.slug %}class="active" {% endif %}>
                <a href="{{ item.get_absolute_url }}">{{ item.name }}</a>
            </li>
        {% endfor %}
    </ul>

            </div>
            <div style="background-color: #fff;padding: 5px">
                <h3>search in products</h3>
                <form class="navbar-form" method='GET' action='' >
                    <div class="input-group">
                        <input class="form-control" placeholder="search" name="q" type="text" value='{{ request.GET.q }}'>
                        <div class="input-group-btn">
                            <button class="btn btn-default" type="submit"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

</div>
<div class="col-sm-9" style="padding:10px 20px">
{% if drugs %}


<div class='' style="background-color: #fff; padding: 5px">
    <div class="text-center row">

        <h1 style="color: #951768;">products</h1>
    </div>

    <br>


    <div class="row" style="">


        <div style="width: 95%;margin: auto">
            {% for item in drugs %}
                <div class="col-md-3 col-sm-6 col-xs-12" style="height: 350px;padding: 10px;border: 1px solid silver">
                    <div class="product-img" style="height: 200px;background-image: {% if item.drug_pic %} url('{{ item.drug_pic.url }}'){% else %}url('{% static 'icons/drugs.png' %}'){% endif %};background-size: contain;background-repeat: no-repeat;background-position: center">
                        {% if item.price == 0 %}
                        <div class="circle" style="position: absolute;top: 20px;left: 20px;height: 50px;width: 50px;border-radius: 100%;background-color: #1e7e34;align-items: center">
                            <p class="text-center" style="color: white;margin: 15px 0">Free!</p>
                        </div>
                        {% endif %}
                        <div class="opa-0" >

                            <div class="well" style="height: 150px;overflow: scroll;margin-bottom: 10px">
                                {{ item.description }}
                            </div>
                            <div class="text-center">
                                <a class="btn btn-success" href="{% url 'product:detail' item.slug %}" data-toggle="popover" data-trigger="hover" data-content="more details" data-placement="left"><i class="fa fa-search" aria-hidden="true" ></i></a>
                                <a class="btn btn-success"  onclick="add_to_cart({{ item.pk }})" data-toggle="popover" data-trigger="hover" data-content="add to cart"><i class="fa fa-shopping-basket" aria-hidden="true"></i></a>
                            </div>
                        </div>
                    </div>

                    <div>
                        <h4 class="">{{ item.drug_name }}</h4>
                        <p >
                            {% if item.price == 0 %}
                            <span class="disabled" style="font-size: 17px">Free!!</span>
                            {% else %}
                            <span class="disabled" style="font-size: 17px">{{ item.price }}</span>
                            {% endif %}

                        </p>
                    <div style="border-top: 1px solid silver;width: 100%;position: absolute;bottom: 0px;left: 0">
                        <div class="col-xs-6" style="padding: 0">
                             <a class="btn" onclick="add_to_cart({{ item.pk }})" style="width: 100%;border-right: 1px solid silver;border-radius: 0;" data-toggle="popover" data-trigger="hover" data-content="add to cart"> <i class="fa fa-shopping-basket" aria-hidden="true"></i></a>
                        </div>
                        <div class="col-xs-6" style="padding: 0">
                            <a class="btn " href="{% url 'product:detail' item.slug %}" data-toggle="popover" data-trigger="hover" data-content="more details" data-placement="left" style="width: 100%;border-left: 1px solid silver;border-radius: 0"><i class="fa fa-search" aria-hidden="true" ></i></a>
                        </div>
                    </div>


                    </div>
                </div>
            {% endfor %}
        </div>
    </div>


    <div class="row text-center">
        <ul class="pagination">
   <li>
        {% if drugs.has_previous %}
            <a href="?{{ page_request_var }}={{ drugs.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-arrow-left" aria-hidden="true"></i></a>
        {% else %}
{#            <a class="disabled"><i class="fa fa-arrow-left" aria-hidden="true"></i></a>#}
        {% endif %}
    </li>
    <li>
        <a class="disabled">page{{ drugs.number }} / {{ drugs.paginator.num_pages }} </a>
    </li>

     <li>
        {% if drugs.has_next %}
            <a href="?{{ page_request_var }}={{ drugs.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        {% else %}
{#            <a class="disabled"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>#}
        {% endif %}
    </li>
  </ul>
    </div>


</div>



{% else %}
    <div style="height: 60vh;background-color: #fff">
    <div style="background-color: #fff">
    <h3 class="text-center">oops this categoury is empty</h3>
    </div>
    </div>
{% endif %}
</div>
</div>
</div>
{% endblock %}