Product/urls.py
from django.conf.urls import url
from . import views

app_name = 'product'


urlpatterns = [
    url(r'^$', views.index, name = 'index'),
    url (r'^(?P<category_slug>[-\w]+)/$', views.index, name='product_list_by_category'),
    url (r'^Drug/(?P<drug_slug>[-\w]+)/$', views.details, name='detail'),

    # comment url
    url(r'^comment/create-comment/', views.Add_comment, name='add-comment'),
]

cart/urls.py
from django.conf.urls import url
from . import views



app_name='cart'
urlpatterns = [
    url(r'^$', views.cart_detail, name = 'cart_detail'),
    url(r'^add/(?P<drug_id>\d+)/$', views.cart_add, name= 'cart_add'),
    url(r'^remove/(?P<drug_id>\d+)/$', views.cart_remove, name= 'cart_remove')

]

pharmacy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url,include
from django.contrib import admin
from .views import Home, Privacy, Terms,test,contact_us
from django.contrib.auth.views import password_reset,password_reset_done,password_reset_confirm, password_reset_complete

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', Home,name='home'),
    url(r'^privacy-and-policy$',Privacy , name='privacy'),
    url(r'^Terms-and-conditions$', Terms, name='terms'),
    url(r'^compound-info/', include('medicalspa.urls', namespace='compound-info')),
    url(r'^emergency/', include('emergency.urls', namespace='emergency')),
    url(r'^orders/', include('orders.urls', namespace='orders')),
    url(r'^product/', include('Product.urls')),
    url(r'^cart/', include('cart.urls', namespace='cart')),
    url(r'^refill/', include('refill.urls', namespace='refill')),
    url(r'^user/', include('user_profile.urls')),

    # password
    url(r'password/$', password_reset,{'template_name': 'password_reset/password_reset.html'}, name='reset_password'),
    url(r'password/done/$', password_reset_done,{'template_name': 'password_reset/password_reset_done.html'}, name='password_reset_done'),
    url(r'password/confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$', password_reset_confirm,{'template_name': 'password_reset/password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'password/complete/$', password_reset_complete,{'template_name': 'password_reset/password_reset_complete.html'},  name='password_reset_complete'),

    # test
    url(r'^test/',test ),

    # other
    url(r'^contact-us$', contact_us,name='contact-us'),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

refill/urls.py
from django.conf.urls import url
from . import views

app_name= 'refill'
urlpatterns= [
    url(r'^new-rx/$', views.new_rx, name='new-rx'),
    url(r'^new-rx/checkout/(?P<pk>[0-9]+)/$', views.NewRx_checkout, name='new-rx-checkout'),
    url(r'^new-rx/checkout-payment/$', views.NewRx_CheckoutView.as_view(), name='newrx-checkoutview'),
    url(r'^new-rx/checkout-successful/$', views.Checkout_Successfull, name='new-rx-checkout-successful'),
    # report html
    url(r'^report/NewRx/$', views.report_newRx, name='report'),
    url(r'^report/NewRx-as-guest/$', views.report_newRx_asguest, name='report-newrx'),
    url(r'^report/refill-as-guest/$', views.report_refill_asguest, name='report-refill'),
    # ajax
    url(r'^ajax/$', views.ajax, name='ajax'),

    # qeust
    url(r'^refill_as_qeust/$', views.refill_as_qeust, name='refill-as-qeust'),
    url(r'^newrx_as_qeust/$', views.newrx_as_qeust, name='newrx-as-qeust'),


    # one click refill
    url(r'^$', views.refill_objects_list, name='refill'),
    url(r'^easy-refill/(?P<pk>[0-9]+)/$', views.refill_submit, name='refill-submit'),


]

user_profile/urls.py
from django.conf.urls import url
from . import views
from refill.views import refill_objects_list,refill_submit
app_name = 'user_profile'

urlpatterns = [
    url(r'^register', views.UserFormView.as_view(), name = 'register'),
    url(r'^login', views.LoginView.as_view(), name = 'login'),
    url(r'^logout', views.Logout, name = 'logout'),

    # userinfo
    url(r'^create-info', views.user_info, name='create-userinfo'),
    #consulting
    url(r'^consulting/ask', views.consulting_ask, name='consulting_ask'),
    url(r'^consulting/show/(?P<pk>[0-9]+)/$', views.consulting_show, name='consulting-show'),
    url(r'^consulting/$', views.consulting, name='consulting'),
    url(r'^consulting-as-guest/$', views.consultiong_as_qeust_view, name='consulting-as-guest'),
    url(r'^report/consulting-as-guest/$', views.report_consulting_asguest, name='report-consulting-as-guest'),
    #profile
    url(r'^$', views.profile, name='profile'),
    url(r'^update', views.EditView.as_view(), name='update'),
    url(r'^changepassword', views.ChangePassword, name='password'),

    url(r'^orders', views.order, name='orders'),
    url(r'^orders', views.order, name='orders'),


    # add phone
    url(r'^add-phone', views.add_phone, name='add-phone'),

]

user_profile/models.py
from django.core.validators import RegexValidator
from django.db import models
from django.contrib.auth.models import AbstractUser
from phonenumber_field.modelfields import PhoneNumberField
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.conf import settings

class User(AbstractUser):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True,null=True)



class UserInfo(models.Model):
    user= models.ForeignKey(User,related_name='info')
    address = models.CharField( max_length=200)
    zip = models.CharField(max_length=20)
    city = models.CharField(max_length=50)

    def __str__(self):
        return self.user.username



class Question(models.Model):
    user=models.ForeignKey(User,blank=True,null=True)
    body=models.TextField()
    date=models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return 'Question :'+ self.body

class Answer(models.Model):
    parrent=models.ForeignKey(Question, related_name='answer')
    body = models.TextField()
    user=models.ForeignKey(User,blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)

    def save(self):
        message = 'answer to your question \n {answer}'.format(answer=self.body)
        msg_html = render_to_string('email/one_text.html',
                                    {'text': message})
        send_mail('answer to your question', 'answer to your question',
                  settings.DEFAULT_FROM_EMAIL, [self.parrent.user.email], fail_silently=False, html_message=msg_html),



class consult_as_guest(models.Model):
    phone_regex = RegexValidator(regex=r'^\+?1?\d{9,15}$',
                                 message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.")
    first_name = models.CharField(max_length=50, null=True, blank=True)
    last_name = models.CharField(max_length=50, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    Email = models.EmailField(null=True)
    Phone_number = models.CharField(validators=[phone_regex], max_length=17, blank=True,
                                    null=True)
    question = models.CharField(max_length=200, null=True)

    class Meta:
        ordering= ('-created',)

    def __str__(self):
        return self.first_name + self.last_name

user_profile/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404
from django.contrib.auth import authenticate, login,logout,update_session_auth_hash
from django.conf import settings
from .form import UserForm,LoginForm,UserInfoForm, QuestionForm, AnswerForm,PhoneForm,consulting_as_guest_Form
from django.contrib.auth import login as auth_login
from django.views.generic import View
from django import forms
from django.http import HttpResponse, HttpResponseRedirect
from .models import Question, Answer, User,UserInfo, consult_as_guest
from django.contrib.auth.decorators import login_required
from django.views.generic.edit import UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy
from emergency.models import Emergency_Med
from refill.models import NewRx,Drug
from orders.models import Order
from refill.views import new_rx
from django.http import JsonResponse
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.forms import PasswordChangeForm
from django.db.models import Sum,Count
from django.core.mail import send_mail
from django.template.loader import render_to_string
from pharmacy.report import render_to_pdf
from pharmacy.twilio import send_sms, send_fax

@login_required(login_url='user_profile:login')
def profile(request):
    current_user= request.user

    # emergency
    eme_all=Emergency_Med.objects.filter(info__user=current_user)
    eme_verified=eme_all.filter(verified=True)

    # refill
    refill_all=NewRx.objects.filter(info__user=current_user)
    refill_verfied=refill_all.filter(verified=True)
    refill_pay=refill_verfied.filter(paid=False)

    # free product order
    free_product_all=Order.objects.filter(info__user=current_user)
    free_product_verified=free_product_all.filter(verified=True)
    # consulting
    question = Question.objects.filter(user=request.user).annotate(answer_count=Count('answer'))
    answer=Answer.objects.filter(parrent__in=question)

    info=UserInfo.objects.filter(user=current_user)
    context={
        'user': current_user,
        # emergency
        'eme_all': eme_all,
        'eme_verified':eme_verified,
        # refil
        'refill_all':refill_all,
        'refill_verfied':refill_verfied,
        'refill_pay':refill_pay,
        # free product
        'free_all':free_product_all,
        'free_verified':free_product_verified,
        # consulting
        'questions':question,
        'answer':answer,
        'info':info,
    }
    return render_to_response('user_profile/dashboard.html', context)


class UserFormView(View):
    form_class = UserForm
    template_name = 'user_profile/register_form.html'
    #
    def get(self, request):
        if request.user.is_authenticated():
            return redirect('home')
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            email = form.cleaned_data['email']
            user.username=email
            user.save()
            karbar = authenticate(username=email, password=password)

            if user is not None:
                if user.is_active:
                    login(request, user)
                    try:
                        return redirect(request.GET['next'])
                    except:
                        return redirect('home')
        return render(request, self.template_name, {'form': form})


class LoginView(View):
    template_name = 'user_profile/login.html'
    def get(self, request):
        if request.user.is_authenticated():
            return redirect('home')
        form = LoginForm()
        return render(request, self.template_name, {
            'form': form
        })

    def post(self, request):
        if request.user.is_authenticated():
            return redirect('user_profile:index')

        form = LoginForm(data=request.POST)
        if form.is_valid():

            user = form.get_user()
            auth_login(request, user)
            try:
                redirect_to=request.GET['next']
                return redirect(request.GET['next'])
            except:
                pass

            return redirect('home')

        return render(request, self.template_name, {
            'form': form
        })

def Logout(request):
    logout(request)
    return redirect('home')

@login_required(login_url='user_profile:login')
def user_info(request):
    if request.method=='POST':
        form=UserInfoForm(data=request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            post.user=request.user
            post.save()
            return redirect(request.GET['next'])
        else:
            return redirect(request.GET['next'])
    else:
        form=UserInfoForm()
        return render(request,'user_profile/form.html',{'form':form})

@login_required(login_url='user_profile:login')
def ChangePassword(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('user_profile:profile')
        return render(request, 'user_profile/change_password.html', {'form': form})
    else:
        form = PasswordChangeForm(user=request.user)
        context = {'form': form}
        return render(request, 'user_profile/change_password.html', context)

class EditView(LoginRequiredMixin, UpdateView):
    login_url = 'user_profile:login'
    model = User
    template_name = 'user_profile/form.html'
    fields = ['first_name', 'last_name', 'email']
    def get_object(self, queryset=None):
        return self.request.user

    success_url = reverse_lazy('user_profile:profile')



@login_required(login_url='user_profile:login')
def consulting_ask(request):
    if request.method=='GET':
        return render(request, 'consulting/consulting-ask.html')
    else:
        form = QuestionForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.user = request.user
            post.save()
            # email
            message = 'Your Question is successfuly submited, our Pharmacist will get back to you soon'  # todo type proprate message here(consulting question shoma sabt shod, zoodi javab midim )
            msg_html = render_to_string('email/one_text.html',
                                        {'text': message})
            send_mail('Question is successfuly submited', 'Question is successfuly submited',
                      settings.DEFAULT_FROM_EMAIL, [request.user.email], fail_silently=False, html_message=msg_html),
            return redirect('user_profile:consulting-show', pk=post.pk)
        else:
            return HttpResponse(form.errors)

@login_required(login_url='user_profile:login')
def consulting(request):
    question=Question.objects.filter(user=request.user)
    return render(request,'consulting/consulting.html',{'question':question})

@login_required(login_url='user_profile:login')
def consulting_show(request,pk):
    if request.method == 'GET':
        question=Question.objects.filter(user=request.user)
        question_show=Question.objects.get(pk=pk)
        answer=Answer.objects.filter(parrent=question_show)
        return render(request, 'consulting/consulting-show.html', {'question': question,'question_show':question_show,'answer':answer})
    else:
        form = AnswerForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            parrent = Question.objects.get(pk=pk)
            post.parrent = parrent
            post.user = request.user
            post.save()
            return redirect('user_profile:consulting-show', pk=pk)
        else:
            return HttpResponse(form.errors)

@csrf_exempt
def add_phone(request):
    user=request.user
    if request.method == 'POST':
        form=PhoneForm(request.POST)
        if form.is_valid():
            post=form.save(commit=False)
            user=request.user
            user.phone_number=post.phone_number
            user.save()
            res='okkk'
        res=form.errors
        result={
            'result':res
        }
        return JsonResponse(result)
    else:
        form = PhoneForm({'add_phone':request.user.phone_number})
        return render(request,'user_profile/form.html',{'form':form})

@login_required(login_url='user_profile:login')
def order(request):
    newrx = NewRx.objects.filter(info__user=request.user).filter(refill=False).annotate(price=Sum('drug__drug_price'))
    refill = NewRx.objects.filter(info__user=request.user).filter(refill=True).annotate(price=Sum('drug__drug_price'))
    shop=Order.objects.filter(info__user=request.user)
    context = {
        'newrx': newrx,
        'refill': refill,
        'shop':shop
    }
    if request.method=='POST':
        canselobj=NewRx.objects.get(pk=request.POST['pk'])
        canselobj.cansel=True
        canselobj.save()
        pdf = render_to_pdf('report/refill-report.html')  # todo send fax for canselation
    return render(request,'user_profile/orders.html',context)


def consultiong_as_qeust_view(request):
    #info=UserInfo.objects.filter(user=request.user)
    #user= User.objects.filter(pk=request.user.id)
    if request.method=='POST':
        form = consulting_as_guest_Form(request.POST)
        if form.is_valid():
            consulting_guest = form.save(commit=False)
            consulting_guest.save()
            contect = {
                'consulting_guest': consulting_guest,
            }
            # email

            message = 'Your question is successfully submited, we will answere it as soon as possible'

user_profile/templates/base/profile-base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8">
    <meta name="keywords" content="">
      <meta name="description" content="">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
{#    <link rel="stylesheet" href="{% static 'cmd/bootstrap.min.css' %}">#}
    <script src="{% static 'cmd/jquery-3.1.1.js' %}"></script>
    <script src="{% static 'cmd/bootstrap.js' %}"></script>
    <script src="{% static 'font-awesome/css/fontawesome-all.js' %}"></script>
    <link rel="stylesheet" href="{% static 'font-awesome/css/font-awesome.min.css' %}">
    {% block style %}{% endblock %}
  <style>
    @font-face {
        font-family: 'IRANSans';
        src: url('{% static 'font/IRANSans.ttf' %}') format('truetype');
        font-weight: normal;
        font-size: 17px;
        font-style: normal;
        }
    .row.content {height: 550px}
    *{
        font-family: IRANSans, tahoma, verdana, sans-serif;

    }

    .sidenav {

      height: 100vh;

    }
    .limargin{
        margin-left: 10px;
    }

    @media screen and (max-width: 767px) {
      .row.content {height: auto;}
    }

    .pf-section{
        background-image: linear-gradient(-135deg,#21254e,#232c58 19%,#232c58 0,#232c58 0,#232d5a 23%,#232d5a 0,#24305d 40%,#24305d 0,#24305d 0,#2b4a83 87%);
    text-align: center;
    position: relative;
    top: -73px;
    width: 100%;
    height: 260px;
    margin-right: -20%;
    margin-bottom: -50px;
    padding-top: 65px;
    border-radius: 856px/188px
    }
    .sidenavlist>li>a{
        color: #474747;
        transition: 0.5s;
    }
      .sidenavlist>li.active>a{
          background-color: silver;
          color: black;
      }
      .sidenavlist>li.active>a:hover{
          background-color: silver;
          color: black;
      }
      .top-nav>ul>li>a{
          color: white;
      }
      .top-nav>ul>li>a:hover{
          color: black;
      }
      .navright{
           height: 100%;
          width: inherit;
          background-color: #fff;
          box-shadow:10px 10px 10px #c6c6c6;
          overflow: hidden
      }
  </style>


            <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-119017928-1"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-119017928-1');
    </script>

</head>
<body style="background-color: #eeeeee">



<nav class="navbar navbar-inverse visible-xs " style="background-color: white;border: none">
  <div class="container-fluid">
    <div class="navbar-header " style="color: #951768">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <i class="fa fa-bars"></i>
      </button>
      <a href="{% url 'home' %}" class="navbar-brand" style="font-family: 'Arial Black';text-decoration: none;font-size: 30px;color: black;">Tyson<span style="color: #951768">Pharmacy</span></a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav" >
        <li class="dashboard " name="dashboard"><a href="{% url 'user_profile:profile' %}"><i class="fas fa-sliders-h"></i><span class="limargin"> Dashboard</span></a></li>
        <li class="order" name="order"><a href="{% url 'user_profile:orders' %}"><i class="fas fa-shopping-cart"></i><span class="limargin"> Orders</span></a></li>
        <li class="ocr" name="ocr"><a href="{% url 'refill:refill' %}"><i class="fas fa-sync-alt"></i><span class="limargin"> Refill</span></a></li>
        <li class="consulting" name="consulting"><a href="{% url 'user_profile:consulting' %}"><i class="fa fa-question" aria-hidden="true"></i></i><span class="limargin">  Consulting</span></a></li>

        <li name="" class="dropdown setting"><a class="dropdown-toggle" data-toggle="dropdown" href="#section3"><i class="fa fa-fw fa-cog"></i><span class="limargin">Setting <span class="caret"></span></span></a>
            <ul class="dropdown-menu">
                 <li class="limargin"><a href="{% url 'user_profile:update' %}">Information</a></li>
                <li><a href="{% url 'user_profile:add-phone' %}">Edit phone number</a></li>
                 <li><a href="{% url 'user_profile:password' %}">Change password</a></li>
                <li><a href="{% url 'user_profile:create-userinfo' %}">Add delivery info</a></li>
            </ul>
        </li>

        <li><a href="{% url 'user_profile:logout' %}"><i class="fas fa-sign-out-alt"></i><span class="limargin">log out</span></a></li>
      </ul>
    </div>
  </div>
</nav>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav hidden-xs" style="padding: 0">
        <div class="affix navright" style="">
      <div class="pf-section" >
          <br>
          <img src="" width="100px" alt="">
          <h3 style="color: white">{{ user.get_full_name }}</h3>
      </div>
        <div style="padding: 10px">
      <ul class="nav nav-pills nav-stacked sidenavlist">

        <li class="dashboard " name="dashboard"><a href="{% url 'user_profile:profile' %}"><i class="fas fa-sliders-h"></i><span class="limargin"> Dashboard</span></a></li>
        <li class="order" name="order"><a href="{% url 'user_profile:orders' %}"><i class="fas fa-shopping-cart"></i><span class="limargin"> Orders</span></a></li>
        <li class="ocr" name="ocr"><a href="{% url 'refill:refill' %}"><i class="fas fa-sync-alt"></i><span class="limargin"> Refill</span></a></li>
        <li class="consulting" name="consulting"><a href="{% url 'user_profile:consulting' %}"><i class="fa fa-question" aria-hidden="true"></i></i><span class="limargin">  Consulting</span></a></li>
        <li name="" class="dropdown setting"><a class="dropdown-toggle" data-toggle="dropdown" href="#section3"><i class="fa fa-fw fa-cog"></i><span class="limargin">Setting <span class="caret"></span></span></a>
            <ul class="dropdown-menu">
                 <li ><a href="{% url 'user_profile:update' %}">Information</a></li>
                <li><a href="{% url 'user_profile:add-phone' %}">Edit phone number</a></li>
                 <li><a href="{% url 'user_profile:password' %}">Change password</a></li>
                <li><a href="{% url 'user_profile:create-userinfo' %}">Add delivery info</a></li>
            </ul>
        </li>


      </ul><br>
            </div>
        </div>
    </div>


    <div class="col-sm-9" style="padding: 0">
  <div class="container-fluid " id="nav" style="background-color: #5c5d70">

    <div class="collapse navbar-collapse top-nav" id="bs-example-navbar-collapse-1" >
      <ul class="nav navbar-nav">
        <li><a href="{% url 'home' %}" style="font-family: 'Arial black';font-size: 30px">TYSONS Pharmacy</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li class=""><a href="{% url 'product:index' %}" style="">Shop</a> </li>
          <li class=""><a href="{% url 'refill:new-rx' %}" style="">New prescription</a> </li>
          <li class=""><a href="" style="">{{ user.get_full_name}}</a> </li>
          <li><a href="{% url 'user_profile:logout' %}" style="">Log out <i class="fas fa-sign-out-alt"></i></a></li>
      </ul>
    </div>

  </div>
        {% block content %}{% endblock %}

    </div>
  </div>
</div>
<script>
    $(document).ready(function () {
        $('.{% block activeClass %}{% endblock %}').addClass('active');
    })
</script>
</body>
</html>